# Generated by Django 5.0 on 2024-02-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='сategory',
            new_name='Category',
        ),
    ]
