# Generated by Django 5.0 on 2024-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('surname', models.CharField(max_length=15, verbose_name='Фамилия')),
                ('gaming_number', models.IntegerField(verbose_name='Игровой номер')),
                ('amplua', models.CharField(max_length=15, verbose_name='Амплуа')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
    ]
