# Generated by Django 5.0 on 2024-02-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='amplua',
            field=models.CharField(choices=[('ДО', 'Доигровщик'), ('ЦБ', 'Центральный блокирующий'), ('СВ', 'Связующий'), ('ДИ', 'Диагональный'), ('ЛИ', 'Либеро')], max_length=15, verbose_name='Амплуа'),
        ),
    ]
