# Generated by Django 5.0 on 2024-02-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_players_amplua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='amplua',
            field=models.CharField(choices=[('', 'Выберите амплуа'), ('ДО', 'Доигровщик'), ('ЦБ', 'Центральный блокирующий'), ('СВ', 'Связующий'), ('ДИ', 'Диагональный'), ('ЛИ', 'Либеро')], max_length=15, verbose_name='Амплуа'),
        ),
    ]
