# Generated by Django 5.0 on 2024-05-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_alter_players_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/players', verbose_name='Изображение'),
        ),
    ]
