# Generated by Django 5.0 on 2024-05-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_alter_players_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='decription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
